import { SignOutButton, UserButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { useRouter } from "next/navigation";
import LoadingPage from "~/components/loading/LoadingPage";
import { Button } from "~/components/ui/button";

export default function Home() {
  const { user, isLoaded, isSignedIn } = useUser();
  console.log("user = ", user);
  const router = useRouter();
  if (isLoaded && !isSignedIn) {
    router.push("/auth");
    return null;
  }
  if (!isLoaded) return <LoadingPage />;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen items-center justify-center bg-gray-950">
        <SignOutButton>
          <Button variant="secondary">Sign out</Button>
        </SignOutButton>
      </main>
    </>
  );
}
